import type { Plugin } from "../src/notion/plugins.ts";

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
}

export function page(title: string, content: string, connected = false, interactive = false): string {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="회의록, 콘텐츠, 팀 운영까지. 스킬을 고르고 내 내용을 넣어 AI에 바로 요청하세요."><meta name="color-scheme" content="light"><title>${escapeHtml(title)} · INLEVEL9 Skills</title><link rel="stylesheet" href="/style.css"><link rel="icon" href="/skills-logo.png?v=90ab004d" type="image/png">${interactive ? '<script src="/catalog.js" defer></script>' : ""}</head><body><a class="skip" href="#main">본문으로 이동</a><div class="shell"><header><a class="brand" href="/" aria-label="INLEVEL9 Skills 홈"><img class="mark" src="/skills-logo.png?v=90ab004d" width="40" height="40" alt=""><span>INLEVEL9 <span class="brand-light">Skills</span></span></a><nav aria-label="주 메뉴"><a href="/catalog">스킬 찾기</a><a href="/guide">사용 안내</a>${connected ? '<form method="post" action="/auth/logout"><button class="quiet" type="submit">로그아웃</button></form>' : '<a class="nav-note" href="/skills">내 Notion 스킬</a>'}</nav></header><main id="main">${content}</main><footer><span>INLEVEL9 Skills</span><nav class="footer-links" aria-label="서비스 정책 및 관련 안내"><a class="privacy-link" href="/privacy">개인정보처리방침</a><a href="/terms">이용약관</a><a href="https://www.notion.com/help/skills" target="_blank" rel="noopener noreferrer">Notion Skills 알아보기</a></nav></footer></div></body></html>`;
}

export function home(ready: boolean): string {
  return page("내 일에 맞는 AI 스킬", `<section class="hero"><div class="hero-copy"><p class="eyebrow">매번 설명하던 일, 이제 스킬로</p><h1>해야 할 일을 고르면,<br><span>시작이 쉬워져요.</span></h1><p class="lead">회의록 정리, 콘텐츠 기획, 팀의 업무 매뉴얼.<br>예시를 보고 내 내용을 넣어, 평소 쓰는 AI에 요청하세요.</p><a class="primary" href="/catalog">내 일에 맞는 스킬 찾기 <span aria-hidden="true">↗</span></a><p class="helper">회원가입 없이 · 설치 없이 · 예시부터 시작</p></div><aside class="library" aria-label="사용자별 시작하기"><div class="library-top"><span>어떤 일을 하고 계세요?</span><span class="example-label">직접 골라보세요</span></div><a class="sample sample-link" href="/catalog?audience=office"><span class="sample-number">01</span><div><h2>일상 업무를 더 편하게</h2><p>회의록, 이메일, 문서, 이번 주 할 일</p></div><span aria-hidden="true">↗</span></a><a class="sample sample-link" href="/catalog?audience=creator"><span class="sample-number">02</span><div><h2>혼자서도 사업과 콘텐츠를</h2><p>콘텐츠 일정, 캠페인, 고객 문의와 의견</p></div><span aria-hidden="true">↗</span></a><a class="sample sample-link" href="/catalog?audience=team"><span class="sample-number">03</span><div><h2>팀이 함께 일하기 쉽게</h2><p>프로젝트, 업무 보고, 매뉴얼, 온보딩</p></div><span aria-hidden="true">↗</span></a><div class="library-bottom">내가 만들 결과를 보고 선택하세요.</div></aside></section><section class="how"><h2>처음이어도 세 단계면 준비돼요.</h2><ol><li><strong>내 일에 맞는 스킬 선택</strong><p>무엇을 넣고 어떤 결과를 받을지 예시로 확인합니다.</p></li><li><strong>내 내용을 넣고 요청문 만들기</strong><p>정리되지 않은 메모도 괜찮아요. 필요한 조건만 덧붙이세요.</p></li><li><strong>내 AI에 붙여넣기</strong><p>요청문을 복사해 평소 쓰는 AI 대화창에서 답변을 받습니다.</p></li></ol></section><section class="trust"><h2>Notion에 내 스킬이 있나요?</h2><div><p>Notion에 모아 둔 스킬 묶음도 연결해서 가져올 수 있어요.</p>${ready ? '<a class="text-link" href="/auth/notion">Notion으로 연결 →</a>' : '<p class="helper">Notion 연결은 준비 중입니다. 기본 스킬은 지금 둘러볼 수 있어요.</p>'}</div></section>`);
}

export function skills(workspaceName: string, plugins: Plugin[]): string {
  const items = plugins.map((plugin) => `<li class="plugin"><div><h2>${escapeHtml(plugin.name || "이름 없는 스킬 묶음")}</h2><p>${escapeHtml(plugin.description || "Notion에서 공유한 AI 스킬 묶음입니다.")}</p></div><a class="secondary" href="/download/${encodeURIComponent(plugin.id)}" aria-label="${escapeHtml(plugin.name)} 다운로드">다운로드 <span aria-hidden="true">↓</span></a></li>`).join("");
  return page("내 스킬", `<section class="page-heading"><p class="eyebrow">${escapeHtml(workspaceName)}</p><h1>내 스킬 라이브러리</h1><p>Notion에서 공유한 스킬 묶음 ${plugins.length}개를 찾았습니다.</p></section>${plugins.length ? `<ul class="plugins">${items}</ul><div class="helper"><p>다운로드는 Notion이 만든 원본 압축 파일(.tar.gz)입니다.</p><a href="/guide">다운로드한 스킬 사용하기 →</a></div>` : '<div class="empty"><h2>아직 보이는 스킬이 없어요.</h2><p>Notion에 Skills 데이터베이스가 있는지 확인하고, 연결할 때 해당 데이터베이스를 선택해 주세요. 일반 데이터베이스는 Skills 데이터베이스로 전환해야 합니다.</p><a class="primary" href="/auth/notion">공유할 스킬 다시 선택</a></div>'}<div class="account"><a href="/auth/notion">다른 워크스페이스 연결</a><form action="/auth/disconnect" method="post"><button class="quiet" type="submit">Notion 연결 해제</button></form></div>`, true);
}

export function message(title: string, body: string, statusAction = "/auth/notion", label = "Notion 다시 연결"): string {
  return page(title, `<section class="message"><p class="eyebrow">INLEVEL9 Skills</p><h1>${escapeHtml(title)}</h1><p>${escapeHtml(body)}</p><a class="primary" href="${escapeHtml(statusAction)}">${escapeHtml(label)}</a></section>`);
}

export function guide(): string {
  return page("사용 안내", `<article class="prose"><p class="eyebrow">처음 이용하시나요?</p><h1>한 번 따라 하면 익숙해져요.</h1><h2>스킬은 무엇인가요?</h2><p>AI가 특정 일을 할 때 따라야 할 작업 방법입니다. 회의록에서 결정과 제안을 구분하거나, 고객 답변에 확인되지 않은 약속을 넣지 않도록 도와줍니다.</p><h2>1. 하고 싶은 일을 고르세요</h2><p><a href="/catalog">스킬 찾기</a>에서 원하는 작업을 선택하세요. 사용자와 작업 종류로 좁히거나 검색할 수 있습니다. 로그인은 필요하지 않습니다.</p><h2>2. 예시로 먼저 해보세요</h2><p>스킬 화면에서 ‘예시 넣기’를 누르고 ‘요청문 만들기’를 눌러보세요. 오른쪽 결과 예시는 원하는 결과의 모양을 보여주는 작성 예시입니다. 이 사이트가 AI 답변을 실행하는 것은 아닙니다.</p><h2>3. 내 AI 대화창에 붙여넣으세요</h2><p>내 메모나 자료로 내용을 바꾼 다음 요청문을 복사하세요. 평소 사용하는 AI 대화창에 붙여넣으면 됩니다. 입력한 본문은 이 사이트 서버로 전송되지 않으며, 붙여넣는 AI 서비스의 데이터 처리 정책이 적용됩니다. 붙여넣기는 그 대화에 지침을 전달하는 방식이며, 스킬이 자동 설치되지는 않습니다.</p><h2 id="install">반복해서 쓴다면: Claude에 스킬 추가</h2><p>스킬 상세 화면의 ‘스킬 ZIP 다운로드’를 누르세요. Claude의 <strong>Customize → Skills → + → Create skill → Upload a skill</strong>에서 받은 ZIP을 업로드하고 활성화합니다. 코드 실행 기능이 필요하며 회사 계정은 관리자 설정에 따라 업로드가 제한될 수 있습니다. <a href="https://support.claude.com/en/articles/12512180-use-skills-in-claude" target="_blank" rel="noopener noreferrer">Claude 공식 사용 안내</a>에서 현재 화면과 조건을 확인할 수 있습니다.</p><h2>Notion에 있는 내 스킬 가져오기</h2><p>연결 기능이 활성화되면 홈의 ‘Notion으로 연결’로 시작합니다. 사용할 Skills 데이터베이스를 공유하고 ‘내 Notion 스킬’에서 스킬 묶음을 내려받습니다. Notion에서 받은 파일은 원본 .tar.gz이므로, 기본 스킬의 ZIP 업로드와는 설치 방식이 다를 수 있습니다.</p><h2>스킬이 보이지 않을 때</h2><p>일반 데이터베이스가 아닌 Notion Skills 데이터베이스인지, 올바른 워크스페이스에서 해당 데이터베이스를 공유했는지 확인하세요. 연결 제한이나 Skills API 이용 제한은 워크스페이스 관리자의 확인이 필요합니다.</p><h2>MCP와는 어떻게 다른가요?</h2><p>스킬은 일을 처리하는 방법이고, MCP 연결은 AI가 외부 도구나 자료에 접근하는 통로입니다. 기본 스킬의 요청문 만들기에는 MCP나 API 키가 필요하지 않습니다. 외부 자료를 직접 읽거나 수정하는 자동화 연결은 별도 기능입니다.</p><h2>Notion 연결을 끝내려면</h2><p>로그아웃하면 이 브라우저의 로그인 정보가 삭제됩니다. ‘Notion 연결 해제’는 현재 연결의 접근 토큰도 폐기합니다. 로그인은 최대 8시간 유지되며 만료되면 다시 연결합니다.</p><a class="primary" href="/catalog/meeting-notes">회의록 예시로 시작하기 →</a></article>`);
}
